// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts_query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (account_id, name, description, currency_code, created_by_user_id) 
VALUES ($1, $2, $3, $4, $5)
`

type CreateAccountParams struct {
	AccountID       uuid.UUID   `json:"account_id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	CurrencyCode    pgtype.Text `json:"currency_code"`
	CreatedByUserID uuid.UUID   `json:"created_by_user_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.AccountID,
		arg.Name,
		arg.Description,
		arg.CurrencyCode,
		arg.CreatedByUserID,
	)
	return err
}
