// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account_transaction_categories_query.sql

package repository

import (
	"github.com/google/uuid"
)

type AddAccountTransactionCategoriesParams struct {
	CategoryCode          *string   `json:"category_code"`
	AccountID             uuid.UUID `json:"account_id"`
	TransactionCategoryID uuid.UUID `json:"transaction_category_id"`
	Color                 *string   `json:"color"`
}
