// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account_members_query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addAccountMember = `-- name: AddAccountMember :exec
INSERT INTO account_members (account_id, user_id, role) VALUES ($1, $2, $3)
`

type AddAccountMemberParams struct {
	AccountID uuid.UUID `json:"account_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddAccountMember(ctx context.Context, arg AddAccountMemberParams) error {
	_, err := q.db.Exec(ctx, addAccountMember, arg.AccountID, arg.UserID, arg.Role)
	return err
}
