// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories_query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (category_id, account_id, name, type, color) 
VALUES ($1, $2, $3, $4, $5)
`

type CreateCategoryParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	AccountID  uuid.UUID `json:"account_id"`
	Name       string    `json:"name"`
	Type       string    `json:"type"`
	Color      *string   `json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.Exec(ctx, createCategory,
		arg.CategoryID,
		arg.AccountID,
		arg.Name,
		arg.Type,
		arg.Color,
	)
	return err
}
