// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForAddAccountTransactionCategories implements pgx.CopyFromSource.
type iteratorForAddAccountTransactionCategories struct {
	rows                 []AddAccountTransactionCategoriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddAccountTransactionCategories) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddAccountTransactionCategories) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CategoryCode,
		r.rows[0].AccountID,
		r.rows[0].TransactionCategoryID,
		r.rows[0].Color,
	}, nil
}

func (r iteratorForAddAccountTransactionCategories) Err() error {
	return nil
}

func (q *Queries) AddAccountTransactionCategories(ctx context.Context, arg []AddAccountTransactionCategoriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account_transaction_categories"}, []string{"category_code", "account_id", "transaction_category_id", "color"}, &iteratorForAddAccountTransactionCategories{rows: arg})
}
