// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID       uuid.UUID  `json:"account_id"`
	Name            string     `json:"name"`
	Description     *string    `json:"description"`
	CurrencyCode    *string    `json:"currency_code"`
	CreatedByUserID uuid.UUID  `json:"created_by_user_id"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
}

type AccountCategory struct {
	AccountCategoryID uuid.UUID  `json:"account_category_id"`
	CategoryCode      *string    `json:"category_code"`
	ParentID          *uuid.UUID `json:"parent_id"`
	AccountID         *uuid.UUID `json:"account_id"`
	CategoryID        *uuid.UUID `json:"category_id"`
	Color             *string    `json:"color"`
}

type AccountMember struct {
	AccountID uuid.UUID  `json:"account_id"`
	UserID    uuid.UUID  `json:"user_id"`
	Role      string     `json:"role"`
	JoinedAt  time.Time  `json:"joined_at"`
	RemovedAt *time.Time `json:"removed_at"`
}

type Category struct {
	CategoryID uuid.UUID  `json:"category_id"`
	Name       string     `json:"name"`
	Type       string     `json:"type"`
	CreatedAt  time.Time  `json:"created_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type Transaction struct {
	TransactionID     uuid.UUID        `json:"transaction_id"`
	Code              string           `json:"code"`
	AccountID         *uuid.UUID       `json:"account_id"`
	AccountCategoryID *uuid.UUID       `json:"account_category_id"`
	Amount            int32            `json:"amount"`
	Description       *string          `json:"description"`
	Date              time.Time        `json:"date"`
	Version           *int32           `json:"version"`
	AddedBy           *uuid.UUID       `json:"added_by"`
	CreatedAt         time.Time        `json:"created_at"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
}

type User struct {
	UserID              uuid.UUID  `json:"user_id"`
	AuthID              string     `json:"auth_id"`
	Name                string     `json:"name"`
	Email               string     `json:"email"`
	CreatedAt           time.Time  `json:"created_at"`
	LastAccessedAccount *uuid.UUID `json:"last_accessed_account"`
}
