// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	CategoryID      pgtype.Int4        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Type            string             `json:"type"`
	Description     pgtype.Text        `json:"description"`
	TransactionDate pgtype.Date        `json:"transaction_date"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	CreatedAt    time.Time   `json:"created_at"`
}
